export const QUERY_KEYS = {
  PROPERTIES: "PROPERTIES",
  PROPERTIES_CATEGORIES: "PROPERTIES_CATEGORIES",
  PROPERTIES_CATEGORIES_TYPE: "PROPERTIES_CATEGORIES_TYPE",
  USER_PROFILE: "USER_PROFILE",
  AGREEMENTS: "AGREEMENTS",
};

// Constant declarations

const PROPERTIES_PAGE_SIZE = 1000;

export { PROPERTIES_PAGE_SIZE };
